# Config for https://github.com/apps/release-drafter
template: |
  ## Changes

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - plugins:
  -     RisePeopleInc/sentry-sourcemaps-uploader#$PREVIOUS_TAG: ~
  +     RisePeopleInc/sentry-sourcemaps-uploader#$NEXT_TAG: ~
  ```
