version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'RisePeopleInc/sentry-sourcemaps-uploader']
    volumes:
      - ".:/plugin:ro"
