version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'RisePeopleInc/sentry-sourcemaps-uploader']
    volumes:
      - ".:/plugin:ro"
  shell_check:
    image: koalaman/shellcheck
    command: ["--color=always", "/plugin/hooks/command"]
    working_dir: /plugin
    volumes:
      - ".:/plugin:ro"
