name: Upload Sourcemaps to Sentry
description: Upload Sourcemaps to Sentry
author: https://github.com/risepeopleinc
requirements:
  - docker
configuration:
  properties:
    release_name:
      type: string
    sourcemaps_artifact:
      type: string
    auth_token:
      type: string
    org_name:
      type: string
    project:
      type: string
    url_prefix:
      type: string
    strip_prefix:
      type: string
  required:
    - sourcemaps_artifact
    - org_name
    - project
