#!/bin/bash

set -eEuo pipefail

# see https://docs.sentry.io/cli/configuration/#configuration-values
export RELEASE_NAME=${BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_RELEASE_NAME:-}
export SOURCEMAPS_ARTIFACT=$BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_SOURCEMAPS_ARTIFACT
export SENTRY_AUTH_TOKEN=$BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_AUTH_TOKEN
export SENTRY_ORG=$BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_ORG_NAME
export SENTRY_PROJECT=$BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_PROJECT

export URL_PREFIX=""
if [ ! -z $BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_URL_PREFIX ]; then
  export URL_PREFIX=" --url-prefix $BUILDKITE_PLUGIN_SENTRY_SOURCEMAPS_UPLOADER_URL_PREFIX"
fi

ROOT_DIR="$( dirname "${BASH_SOURCE[0]}" )"

on_failure() {
    echo "Command failed with exit status: $?"
    exit $?
}

trap on_failure ERR

[ -e "${SOURCEMAPS_ARTIFACT}" ] || buildkite-agent artifact download ${SOURCEMAPS_ARTIFACT} .

if [ -z "$RELEASE_NAME" ]; then
  RELEASE_NAME=$($ROOT_DIR/sentry-cli releases propose-version)
fi
$ROOT_DIR/sentry-cli releases new $RELEASE_NAME
# allow set-commits to fail since some people won't have VCS integration setup
if [ -e .git ]; then
  $ROOT_DIR/sentry-cli releases set-commits "$RELEASE_NAME" --auto || true
fi
$ROOT_DIR/sentry-cli releases files $RELEASE_NAME upload-sourcemaps ${SOURCEMAPS_ARTIFACT}/* $URL_PREFIX
$ROOT_DIR/sentry-cli releases finalize "$RELEASE_NAME"

